name: 'Stale issue handler'
# Will search once a day at 7:00 for stale issues/PRs (those that have no had updates in 30 days).
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.0.0
        id: stale
        with:
          stale-issue-message: 'This Issue will be closed in 30 days. Please remove the "Stale" label or comment to avoid closure with no action.'
          stale-pr-message: 'This PR will be closed in 30 days. Please remove the "Stale" label or comment to avoid closure with no action.'
          operations-per-run: 200
          days-before-stale: 300
          days-before-close: 30
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          close-issue-label: 'closed'
          close-pr-label: 'closed'
          exempt-issue-labels: 'bug,enhancement,documentation,waiting,keep'
          exempt-all-milestones: true
          exempt-all-assignees: true
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}